name: Release to private Nuget

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./CSharp
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build -c Debug /p:Version=1.4.${{github.run_number}}-debug
    - name: Test
      run: dotnet test -c Debug --no-build
    - name: Build
      run: dotnet build -c Release /p:Version=1.4.${{github.run_number}}-custom
    - name: Pack nugets
      run: dotnet pack -c Release /p:Version=1.4.${{github.run_number}}-custom --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.NUGET_API_KEY }}
